mybatis.mapper-locations: classpath*:/mybatis/*Mapper.xml

server:
  port: 1140

#LogBack日志配置
logging:
    path: /logtext/con/logs/
    level:
        com.zhaojm: debug
    file:
        max-size: 64M

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

  application:
      name: security
      
      
#thymelea模板配置
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
#热部署文件，页面不产生缓存，及时更新
spring.thymeleaf.cache: false
spring.resources.chain.strategy.content.enabled: true
spring.resources.chain.strategy.content.paths: /**