mybatis.mapper-locations: classpath*:/mybatis/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test??useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

spring.redis.database.: 0
spring.redis.host: 127.0.0.1
spring.redis.port: 6379
spring.redis.password:


#LogBack日志配置
logging:
  path: /logs
  log-level: DEBUG
