

mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  #configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#org.apache.ibatis.logging.log4j.Log4jImpl  不打印查询结果
#org.apache.ibatis.logging.stdout.StdOutImpl 打印查询结果

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test??useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  application:
    name: spring-redis

spring.redis.database: 0
spring.redis.host: 127.0.0.1
spring.redis.port: 6379
spring.redis.password:

#LogBack日志配置
logging:
  path: /spring/test/logs/
  level:
    com.zhaojm.redis: debug
  file:
    max-size: 64M
server:
  port: 1120

#注册中心配置参数
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  #config: classpath:log4j2.xml
