mybatis.mapper-locations: classpath*:/mybatis/*Mapper.xml

#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
    
#spring:
#  thymeleaf:
#    cache: false
#    mode: HTML5

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test??useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  application:
    name: spring-date

    
app.session.outtime: 3600
server:
  port: 1130

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

    
    